export const UNIVERSITIES_UK = [
  // England
  "Anglia Ruskin University",
  "Arts University Bournemouth",
  "Aston University",
  "Bangor University",
  "Bath Spa University",
  "Birmingham City University",
  "Birkbeck, University of London",
  "Bournemouth University",
  "Brunel University London",
  "Canterbury Christ Church University",
  "City, University of London",
  "Coventry University",
  "Cranfield University",
  "De Montfort University",
  "Durham University",
  "Edge Hill University",
  "Falmouth University",
  "Goldsmiths, University of London",
  "Harper Adams University",
  "Imperial College London",
  "Keele University",
  "King's College London",
  "Kingston University",
  "Lancaster University",
  "Leeds Beckett University",
  "Liverpool Hope University",
  "Liverpool John Moores University",
  "London Metropolitan University",
  "London South Bank University",
  "Loughborough University",
  "Manchester Metropolitan University",
  "Middlesex University",
  "Newcastle University",
  "Northumbria University",
  "Nottingham Trent University",
  "Oxford Brookes University",
  "Queen Mary University of London",
  "Ravensbourne University London",
  "Roehampton University",
  "Royal Holloway, University of London",
  "Sheffield Hallam University",
  "SOAS University of London",
  "Solent University",
  "Staffordshire University",
  "St George's, University of London",
  "Teesside University",
  "The Open University",
  "The University of Law",
  "University College London",
  "University for the Creative Arts",
  "University of Bath",
  "University of Bedfordshire",
  "University of Birmingham",
  "University of Bolton",
  "University of Bradford",
  "University of Brighton",
  "University of Bristol",
  "University of Buckingham",
  "University of Cambridge",
  "University of Central Lancashire",
  "University of Chester",
  "University of Chichester",
  "University of Cumbria",
  "University of Derby",
  "University of East Anglia",
  "University of East London",
  "University of Essex",
  "University of Exeter",
  "University of Gloucestershire",
  "University of Greenwich",
  "University of Hertfordshire",
  "University of Huddersfield",
  "University of Hull",
  "University of Kent",
  "University of Leeds",
  "University of Leicester",
  "University of Lincoln",
  "University of Liverpool",
  "University of London",
  "University of Manchester",
  "University of Northampton",
  "University of Nottingham",
  "University of Oxford",
  "University of Plymouth",
  "University of Portsmouth",
  "University of Reading",
  "University of Salford",
  "University of Sheffield",
  "University of Southampton",
  "University of Staffordshire",
  "University of Suffolk",
  "University of Sunderland",
  "University of Surrey",
  "University of Sussex",
  "University of the Arts London",
  "University of the West of England",
  "University of Warwick",
  "University of Westminster",
  "University of Winchester",
  "University of Wolverhampton",
  "University of Worcester",
  "University of York",
  "York St John University",

  // Wales
  "Aberystwyth University",
  "Bangor University",
  "Cardiff Metropolitan University",
  "Cardiff University",
  "Swansea University",
  "University of South Wales",
  "University of Wales Trinity Saint David",
  "Wrexham University",

  // Scotland
  "Abertay University",
  "Edinburgh Napier University",
  "Glasgow Caledonian University",
  "Heriot-Watt University",
  "Queen Margaret University",
  "Robert Gordon University",
  "University of Aberdeen",
  "University of Dundee",
  "University of Edinburgh",
  "University of Glasgow",
  "University of St Andrews",
  "University of Stirling",
  "University of Strathclyde",
  "University of the Highlands and Islands",
  "University of the West of Scotland",

  // Northern Ireland
  "Queen's University Belfast",
  "Ulster University",

  // Specialist / private degree-awarding
  "BPP University",
  "Regent's University London",
  "Royal Agricultural University",
  "Royal Central School of Speech and Drama",
  "Royal College of Art",
  "Royal College of Music",
  "Royal Conservatoire of Scotland",
  "Royal Veterinary College"
] as const;