// src/lib/catalog/statutes.ts
import { topicKeysMatch } from "@/lib/topicKeys";

export type Statute = {
  id: string;
  title: string;
  year?: number;
  short?: string;
  url?: string;
  topicKeys: string[];
  subtopics?: string[];
  tags?: string[];
  priority?: "core" | "useful";
};

// Seed data (expandable; later move to Firestore)
export const STATUTES: Statute[] = [
  {
    id: "companies-act-2006",
    title: "Companies Act",
    year: 2006,
    short: "Core UK company law framework: formation, directors, shares, filings, and governance.",
    url: "https://www.legislation.gov.uk/ukpga/2006/46/contents",
    topicKeys: ["BusinessLawandPractice"],
    subtopics: ["Company Formation", "Directors’ Duties", "Share Capital & Pre-emption"],
    priority: "core",
    tags: ["companies", "directors", "shares"],
  },
  {
    id: "insolvency-act-1986",
    title: "Insolvency Act",
    year: 1986,
    short: "Corporate and personal insolvency processes, office-holders, and antecedent transactions.",
    url: "https://www.legislation.gov.uk/ukpga/1986/45/contents",
    topicKeys: ["BusinessLawandPractice"],
    subtopics: ["Insolvency Overview", "Members’ Remedies"],
    priority: "core",
    tags: ["insolvency", "administration", "liquidation"],
  },
  {
    id: "partnership-act-1890",
    title: "Partnership Act",
    year: 1890,
    short: "General law on creation, relations, and dissolution of partnerships.",
    url: "https://www.legislation.gov.uk/ukpga/Vict/53-54/39/contents",
    topicKeys: ["BusinessLawandPractice"],
    subtopics: ["Company Formation"],
    priority: "useful",
    tags: ["partnership", "firm"],
  },
  {
    id: "llp-act-2000",
    title: "Limited Liability Partnerships Act",
    year: 2000,
    short: "Introduces LLPs and key incorporation framework.",
    url: "https://www.legislation.gov.uk/ukpga/2000/12/contents",
    topicKeys: ["BusinessLawandPractice"],
    subtopics: ["Company Formation"],
    priority: "useful",
    tags: ["llp", "incorporation"],
  },
  {
    id: "civil-procedure-rules-1998",
    title: "Civil Procedure Rules",
    year: 1998,
    short: "Primary procedural code for civil litigation in England and Wales.",
    url: "https://www.legislation.gov.uk/uksi/1998/3132/contents/made",
    topicKeys: ["DisputeResolution"],
    subtopics: ["CPR & Overriding Objective", "Case Management & Tracks"],
    priority: "core",
    tags: ["cpr", "procedure"],
  },
  {
    id: "limitation-act-1980",
    title: "Limitation Act",
    year: 1980,
    short: "Sets limitation periods for civil claims.",
    url: "https://www.legislation.gov.uk/ukpga/1980/58/contents",
    topicKeys: ["DisputeResolution", "Tort", "Contract"],
    subtopics: ["Judgment & Enforcement", "Limitation", "Breach & Remedies"],
    priority: "core",
    tags: ["limitation", "time bars"],
  },
  {
    id: "senior-courts-act-1981",
    title: "Senior Courts Act",
    year: 1981,
    short: "Jurisdictional and procedural framework for Senior Courts.",
    url: "https://www.legislation.gov.uk/ukpga/1981/54/contents",
    topicKeys: ["DisputeResolution", "LegalSystemofEnglandandWales"],
    subtopics: ["Court Structure", "Jurisdiction & Commencement"],
    priority: "useful",
    tags: ["courts", "jurisdiction"],
  },
  {
    id: "county-courts-act-1984",
    title: "County Courts Act",
    year: 1984,
    short: "County Court powers, jurisdiction, and process framework.",
    url: "https://www.legislation.gov.uk/ukpga/1984/28/contents",
    topicKeys: ["DisputeResolution", "LegalSystemofEnglandandWales"],
    subtopics: ["Court Structure", "Jurisdiction & Commencement"],
    priority: "useful",
    tags: ["county court", "jurisdiction"],
  },
  {
    id: "consumer-rights-act-2015",
    title: "Consumer Rights Act",
    year: 2015,
    short: "Consumer contract rights and remedies for goods, services, and digital content.",
    url: "https://www.legislation.gov.uk/ukpga/2015/15/contents",
    topicKeys: ["Contract"],
    subtopics: ["Exclusion & Unfair Terms", "Breach & Remedies"],
    priority: "core",
    tags: ["consumer", "contract terms"],
  },
  {
    id: "misrepresentation-act-1967",
    title: "Misrepresentation Act",
    year: 1967,
    short: "Statutory remedies and burden framework for misrepresentation claims.",
    url: "https://www.legislation.gov.uk/ukpga/1967/7/contents",
    topicKeys: ["Contract"],
    subtopics: ["Misrepresentation", "Breach & Remedies"],
    priority: "core",
    tags: ["misrepresentation", "rescission"],
  },
  {
    id: "ucta-1977",
    title: "Unfair Contract Terms Act",
    year: 1977,
    short: "Controls exclusion and limitation clauses using reasonableness tests.",
    url: "https://www.legislation.gov.uk/ukpga/1977/50/contents",
    topicKeys: ["Contract"],
    subtopics: ["Exclusion & Unfair Terms"],
    priority: "core",
    tags: ["unfair terms", "reasonableness"],
  },
  {
    id: "law-reform-frustrated-contracts-act-1943",
    title: "Law Reform (Frustrated Contracts) Act",
    year: 1943,
    short: "Adjusts common law consequences of frustration in contract.",
    url: "https://www.legislation.gov.uk/ukpga/Geo6/6-7/40/contents",
    topicKeys: ["Contract"],
    subtopics: ["Frustration"],
    priority: "useful",
    tags: ["frustration", "restitution"],
  },
  {
    id: "occupiers-liability-act-1957",
    title: "Occupiers' Liability Act",
    year: 1957,
    short: "Duty owed by occupiers to lawful visitors.",
    url: "https://www.legislation.gov.uk/ukpga/Eliz2/5-6/31/contents",
    topicKeys: ["Tort"],
    subtopics: ["Occupiers’ Liability", "Duty & Standard"],
    priority: "core",
    tags: ["occupiers liability", "visitors"],
  },
  {
    id: "occupiers-liability-act-1984",
    title: "Occupiers' Liability Act",
    year: 1984,
    short: "Duty owed by occupiers to non-visitors and trespassers in limited situations.",
    url: "https://www.legislation.gov.uk/ukpga/1984/3/contents",
    topicKeys: ["Tort"],
    subtopics: ["Occupiers’ Liability", "Defences"],
    priority: "core",
    tags: ["trespassers", "occupiers liability"],
  },
  {
    id: "defamation-act-2013",
    title: "Defamation Act",
    year: 2013,
    short: "Modern statutory framework for defamation and related defences.",
    url: "https://www.legislation.gov.uk/ukpga/2013/26/contents",
    topicKeys: ["Tort"],
    subtopics: ["Defences", "Damages"],
    priority: "useful",
    tags: ["defamation", "publication"],
  },
  {
    id: "human-rights-act-1998",
    title: "Human Rights Act",
    year: 1998,
    short: "Incorporates ECHR rights into domestic UK law.",
    url: "https://www.legislation.gov.uk/ukpga/1998/42/contents",
    topicKeys: ["ConstitutionalAdministrativeEULegalServices"],
    subtopics: ["Human Rights (HRA)", "Judicial Review Grounds"],
    priority: "core",
    tags: ["human rights", "public law"],
  },
  {
    id: "constitutional-reform-act-2005",
    title: "Constitutional Reform Act",
    year: 2005,
    short: "Reforms constitutional arrangements including Supreme Court creation.",
    url: "https://www.legislation.gov.uk/ukpga/2005/4/contents",
    topicKeys: ["ConstitutionalAdministrativeEULegalServices", "LegalSystemofEnglandandWales"],
    subtopics: ["Separation of Powers", "Court Structure"],
    priority: "core",
    tags: ["constitutional", "supreme court"],
  },
  {
    id: "legal-services-act-2007",
    title: "Legal Services Act",
    year: 2007,
    short: "Regulatory architecture for reserved legal activities and approved regulators.",
    url: "https://www.legislation.gov.uk/ukpga/2007/29/contents",
    topicKeys: ["ConstitutionalAdministrativeEULegalServices", "SolicitorsAccounts"],
    subtopics: ["Legal Services Regulation", "Breach & Reporting"],
    priority: "core",
    tags: ["regulation", "legal services"],
  },
  {
    id: "lra-2002",
    title: "Land Registration Act",
    year: 2002,
    short: "Registration, priority, notices/restrictions, and overriding interests.",
    url: "https://www.legislation.gov.uk/ukpga/2002/9/contents",
    topicKeys: ["LandLaw", "PropertyPractice"],
    subtopics: ["Registration (LRA 2002)", "Title & Restrictions", "Overriding Interests"],
    priority: "core",
    tags: ["registration", "priority"],
  },
  {
    id: "lpa-1925",
    title: "Law of Property Act",
    year: 1925,
    short: "Conveyancing framework for estates, interests, formalities, and powers.",
    url: "https://www.legislation.gov.uk/ukpga/Geo5/15-16/20/contents",
    topicKeys: ["LandLaw", "PropertyPractice"],
    subtopics: ["Estates & Interests", "Co-ownership", "Contracts & Exchange"],
    priority: "core",
    tags: ["estates", "formalities"],
  },
  {
    id: "landlord-tenant-act-1954",
    title: "Landlord and Tenant Act",
    year: 1954,
    short: "Business tenancy security of tenure and renewal rights.",
    url: "https://www.legislation.gov.uk/ukpga/Eliz2/2-3/56/contents",
    topicKeys: ["LandLaw", "PropertyPractice"],
    subtopics: ["Leases & Licences", "Leasehold Points"],
    priority: "useful",
    tags: ["lease", "security of tenure"],
  },
  {
    id: "trustee-act-1925",
    title: "Trustee Act",
    year: 1925,
    short: "Historic framework for trustee powers and administration.",
    url: "https://www.legislation.gov.uk/ukpga/Geo5/15-16/19/contents",
    topicKeys: ["Trusts", "WillsAndProbate"],
    subtopics: ["Duties & Powers", "PR Duties"],
    priority: "core",
    tags: ["trustees", "administration"],
  },
  {
    id: "trustee-act-2000",
    title: "Trustee Act",
    year: 2000,
    short: "Modernized trustee powers, investment standards, and duties of care.",
    url: "https://www.legislation.gov.uk/ukpga/2000/29/contents",
    topicKeys: ["Trusts"],
    subtopics: ["Duties & Powers", "Breach & Remedies"],
    priority: "core",
    tags: ["trustee powers", "investment"],
  },
  {
    id: "tolata-1996",
    title: "Trusts of Land and Appointment of Trustees Act",
    year: 1996,
    short: "Core statutory framework for trusts of land and co-ownership disputes.",
    url: "https://www.legislation.gov.uk/ukpga/1996/47/contents",
    topicKeys: ["Trusts", "LandLaw"],
    subtopics: ["Formalities for Land", "Co-ownership"],
    priority: "core",
    tags: ["tolata", "co-ownership"],
  },
  {
    id: "wills-act-1837",
    title: "Wills Act",
    year: 1837,
    short: "Main statutory formalities and execution requirements for wills.",
    url: "https://www.legislation.gov.uk/ukpga/Will4and1Vict/7/26/contents",
    topicKeys: ["WillsAndProbate"],
    subtopics: ["Formalities", "Will Construction"],
    priority: "core",
    tags: ["wills", "execution"],
  },
  {
    id: "administration-of-estates-act-1925",
    title: "Administration of Estates Act",
    year: 1925,
    short: "Rules for estate administration, personal representatives, and distribution.",
    url: "https://www.legislation.gov.uk/ukpga/Geo5/15-16/23/contents",
    topicKeys: ["WillsAndProbate"],
    subtopics: ["PR Duties", "Intestacy", "Grants"],
    priority: "core",
    tags: ["estate administration", "personal representatives"],
  },
  {
    id: "inheritance-family-provision-act-1975",
    title: "Inheritance (Provision for Family and Dependants) Act",
    year: 1975,
    short: "Allows eligible applicants to claim reasonable financial provision from estates.",
    url: "https://www.legislation.gov.uk/ukpga/1975/63/contents",
    topicKeys: ["WillsAndProbate"],
    subtopics: ["Family Provision (1975 Act)", "PR Duties"],
    priority: "core",
    tags: ["family provision", "dependants"],
  },
  {
    id: "solicitors-act-1974",
    title: "Solicitors Act",
    year: 1974,
    short: "Key statutory framework for solicitors, including practising and client-related controls.",
    url: "https://www.legislation.gov.uk/ukpga/1974/47/contents",
    topicKeys: ["SolicitorsAccounts"],
    subtopics: ["Client vs Office Money", "Breach & Reporting"],
    priority: "core",
    tags: ["solicitors", "professional regulation"],
  },
  {
    id: "proceeds-of-crime-act-2002",
    title: "Proceeds of Crime Act",
    year: 2002,
    short: "Money laundering offences, reporting, and confiscation framework.",
    url: "https://www.legislation.gov.uk/ukpga/2002/29/contents",
    topicKeys: ["SolicitorsAccounts", "CriminalPractice"],
    subtopics: ["MLR & CDD", "Procedure"],
    priority: "core",
    tags: ["aml", "money laundering"],
  },
  {
    id: "theft-act-1968",
    title: "Theft Act",
    year: 1968,
    short: "Core property offence definitions including theft, robbery, and burglary structures.",
    url: "https://www.legislation.gov.uk/ukpga/1968/60/contents",
    topicKeys: ["CriminalPractice"],
    subtopics: ["Property Offences", "Elements (AR/MR)"],
    priority: "core",
    tags: ["theft", "dishonesty"],
  },
  {
    id: "offences-against-person-act-1861",
    title: "Offences Against the Person Act",
    year: 1861,
    short: "Principal offences against the person still used in modern criminal practice.",
    url: "https://www.legislation.gov.uk/ukpga/Vict/24-25/100/contents",
    topicKeys: ["CriminalPractice"],
    subtopics: ["Offences Against the Person", "Elements (AR/MR)"],
    priority: "core",
    tags: ["violence offences", "criminal"],
  },
  {
    id: "criminal-attempts-act-1981",
    title: "Criminal Attempts Act",
    year: 1981,
    short: "Inchoate offences framework for attempts and related liability.",
    url: "https://www.legislation.gov.uk/ukpga/1981/47/contents",
    topicKeys: ["CriminalPractice"],
    subtopics: ["Inchoate Liability", "Elements (AR/MR)"],
    priority: "core",
    tags: ["attempts", "inchoate"],
  },
  {
    id: "pace-1984",
    title: "Police and Criminal Evidence Act",
    year: 1984,
    short: "Police powers and safeguards on stop/search, arrest, detention, and evidence.",
    url: "https://www.legislation.gov.uk/ukpga/1984/60/contents",
    topicKeys: ["CriminalPractice"],
    subtopics: ["Procedure", "Bail"],
    priority: "core",
    tags: ["pace", "police powers"],
  },
  {
    id: "criminal-justice-act-2003",
    title: "Criminal Justice Act",
    year: 2003,
    short: "Major reforms affecting evidence, procedure, and sentencing.",
    url: "https://www.legislation.gov.uk/ukpga/2003/44/contents",
    topicKeys: ["CriminalPractice"],
    subtopics: ["Sentencing", "Procedure"],
    priority: "core",
    tags: ["sentencing", "criminal procedure"],
  },
];

export function statutesForTopicKey(topicKey: string): Statute[] {
  if (!topicKey) return [];
  return STATUTES.filter((s) =>
    s.topicKeys.some((k) => topicKeysMatch(k, topicKey)),
  ).sort((a, b) => {
    const pa = a.priority === "core" ? 0 : 1;
    const pb = b.priority === "core" ? 0 : 1;
    if (pa !== pb) return pa - pb;
    return a.title.localeCompare(b.title);
  });
}
